In [6]:
import numpy as np

def game_of_life(size: tuple, generations: int = 100) -> np.ndarray:
    """
    Simulates Conway's Game of Life on a 2D grid using vectorized NumPy operations.

    Args:
        size (tuple): A 2-element tuple (rows, cols) defining the dimensions of the grid.
        generations (int, optional): The total number of evolution steps to run. 
            Defaults to 100.

    Returns:
        np.ndarray: The final state of the grid after all generations have been processed, 
        represented as a 2D array of 0s (dead cells) and 1s (live cells).
    """
    # Initialize the grid with random binary states (0 for dead, 1 for live)
    grid = np.random.randint(0, 2, size) 

    counter = 1
    while counter <= generations:
        # 1. Compute straight-line neighbors using toroidal wrapping (np.roll)
        up = np.roll(grid, shift=1, axis=0)      # Shift rows down
        down = np.roll(grid, shift=-1, axis=0)   # Shift rows up
        left = np.roll(grid, shift=1, axis=1)    # Shift columns right
        right = np.roll(grid, shift=-1, axis=1)  # Shift columns left

        # 2. Compute diagonal neighbors by shifting across both axes simultaneously
        top_left = np.roll(grid, shift=(1, 1), axis=(0, 1))
        top_right = np.roll(grid, shift=(1, -1), axis=(0, 1))
        bottom_left = np.roll(grid, shift=(-1, 1), axis=(0, 1))
        bottom_right = np.roll(grid, shift=(-1, -1), axis=(0, 1))

        # Aggregate the neighbor count for every cell across all 8 surrounding directions
        neighbor_matrix = up + down + left + right + top_left + top_right + bottom_left + bottom_right
  
        # Create a blank canvas for the next generation to enforce simultaneous updates
        new_grid = np.zeros_like(grid)
        
        # Survival rule: A live cell (1) with 2 or 3 live neighbors stays alive
        survival_mask = (grid == 1) & ((neighbor_matrix == 2) | (neighbor_matrix == 3))
        
        # Reproduction rule: A dead cell (0) with exactly 3 live neighbors becomes alive
        reproduction_mask = (grid == 0) & (neighbor_matrix == 3)
        
        # Apply the masks to populate the new generation grid
        new_grid[survival_mask | reproduction_mask] = 1

        # Advance to the next generation state
        grid = new_grid
        counter += 1

    return grid


if __name__ == "__main__":
    grid = game_of_life(size=(10, 10))
    print(grid)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


![game_of_life.jpeg](<assets/game_of_life.jpeg>)