### **What is numpy?**

**NumPy** is the fundamental package for scientific computing in Python. It is a Python library that provides a **multidimensional array object**, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including:
* Mathematical and logical operations
* Shape manipulation
* Sorting and selecting
* I/O (Input/Output)
* Discrete Fourier transforms
* Basic linear algebra and basic statistical operations
* Random simulation and much more.

At the core of the NumPy package, is the **`ndarray`** object. This encapsulates n-dimensional arrays of homogeneous data types.

---

### **Numpy Arrays Vs Python Sequences**

* **Fixed Size:** NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an `ndarray` will create a new array and delete the original.
* **Homogeneous Elements:** The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.
* **Efficient Processing:** NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.
* **Scientific Ecosystem Standard:** A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### **1. Creating Numpy Arrays**
Below are the fundamental functions used to generate arrays in various dimensions and data types.

In [12]:
import numpy as np

# np.array: Creates an array from a regular Python list or tuple
a = np.array([1, 2, 3]) # it is a 1D array
print("1D Array:\n", a)
print(type(a))

1D Array:
 [1 2 3]
<class 'numpy.ndarray'>


In [6]:
# 2D and 3D array creation
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", b)

c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", c)


2D Array:
 [[1 2 3]
 [4 5 6]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype: Forcing a specific data type during array creation
print("\nFloat array:", np.array([1, 2, 3], dtype=float))
print("Boolean array:", np.array([1, 2, 3], dtype=bool))
print("Complex array:", np.array([1, 2, 3], dtype=complex))


Float array: [1. 2. 3.]
Boolean array: [ True  True  True]
Complex array: [1.+0.j 2.+0.j 3.+0.j]


In [ ]:
# np.arange: Returns evenly spaced values within a given interval (start, stop, step)
print("\nArange (1 to 10):", np.arange(1, 11))
print("Arange with step of 2:", np.arange(1, 11, 2))

In [8]:
# reshape: Gives a new shape to an array without changing its data
print("\nReshape to 5x2:\n", np.arange(1, 11).reshape(5, 2))
print("Reshape to 4x3:\n", np.arange(1, 13).reshape(4, 3))


Reshape to 5x2:
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Reshape to 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# np.ones and np.zeros: Initialize arrays filled entirely with 1s or 0s
print("\nZeros (3x4):\n", np.zeros((3, 4)))
print("Ones (3x4):\n", np.ones((3, 4)))

In [9]:
# np.random: Generates an array with random floats between 0.0 and 1.0
print("\nRandom (3x4):\n", np.random.random((3, 4)))


Random (3x4):
 [[0.40389412 0.09225324 0.57114296 0.51010944]
 [0.30903444 0.69116834 0.82220697 0.23391472]
 [0.56710368 0.33588095 0.48485569 0.09889427]]


In [11]:
# np.linspace: Returns evenly spaced numbers over a specified interval (start, stop, number_of_samples)
print("\nLinspace (10 values from -10 to 10):\n", np.linspace(-10, 10, 10))


Linspace (10 values from -10 to 10):
 [-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [10]:

# np.identity: Returns a square identity matrix (1s on the main diagonal, 0s elsewhere)
print("\nIdentity Matrix (3x3):\n", np.identity(3))


Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### **2. Array Attributes**
Attributes allow you to check the metadata of an array (its shape, size, memory consumption) without changing its underlying data.

In [14]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3, 4)
a3 = np.arange(8).reshape(2, 2, 2)

In [15]:
# ndim: Returns the number of dimensions (axes) of the array
print("Dimensions of a1, a2, a3:", a1.ndim, a2.ndim, a3.ndim)

Dimensions of a1, a2, a3: 1 2 3


In [16]:
# shape: Returns a tuple representing the size of the array in each dimension
print("Shapes of a1, a2, a3:", a1.shape, a2.shape, a3.shape)

Shapes of a1, a2, a3: (10,) (3, 4) (2, 2, 2)


In [17]:
# size: Returns the total number of elements in the array
print("Total size of a1, a2, a3:", a1.size, a2.size, a3.size)

Total size of a1, a2, a3: 10 12 8


In [18]:
# itemsize: Returns the length of one array element in bytes
print("Itemsize (bytes per element):", a1.itemsize, a2.itemsize, a3.itemsize)

Itemsize (bytes per element): 4 8 8


In [19]:
# dtype: Returns the data-type of the array's elements
print("Datatypes:")
print("a1:", a1.dtype)
print("a2:", a2.dtype)
print("a3:", a3.dtype)

Datatypes:
a1: int32
a2: float64
a3: int64


In [20]:
# ndarray.nbytes: Returns the total bytes consumed by the elements of the array
print("Total memory footprint (bytes):")
print("a1 nbytes:", a1.nbytes)
print("a2 nbytes:", a2.nbytes)
print("a3 nbytes:", a3.nbytes)

Total memory footprint (bytes):
a1 nbytes: 40
a2 nbytes: 96
a3 nbytes: 64


### **3. Changing Datatype**
You can cast arrays to new datatypes.

In [21]:
# astype: Casts a copy of the array to a specified type
print("Original a3 dtype:", a3.dtype)
a3 = a3.astype(np.int32)
print("Changed a3 dtype:", a3.dtype)

Original a3 dtype: int64
Changed a3 dtype: int32


### **4. Array Operations**
NumPy also allows mathematical operations directly on arrays (vectorization) without writing `for` loops.

In [22]:
print("\n--- Array Operations ---")
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)


--- Array Operations ---


In [23]:
# Scalor Operations (Operations between an array and a single number)
print("\nScalar Arithmetic (a1 ** 2):\n", a1 ** 2)


Scalar Arithmetic (a1 ** 2):
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [24]:
# Relational Operations (Returns a boolean array)
print("\nRelational (a2 == 15):\n", a2 == 15)


Relational (a2 == 15):
 [[False False False  True]
 [False False False False]
 [False False False False]]


In [25]:
# Vector Operations (Operations between two arrays of the same shape)
print("\nVector Arithmetic (Addition):\n", a1 + a2)
print("\nVector Arithmetic (Subtraction):\n", a1 - a2)
print("\nVector Arithmetic (Exponentiation):\n", a1 ** a2)


Vector Arithmetic (Addition):
 [[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

Vector Arithmetic (Subtraction):
 [[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]

Vector Arithmetic (Exponentiation):
 [[                   0                    1                16384
              14348907]
 [          4294967296         762939453125      101559956668416
     11398895185373143]
 [ 1152921504606846976 -1261475310744950487  1864712049423024128
   6839173302027254275]]


### **5. Array Functions**
NumPy provides highly optimized built-in math functions. 
**Note on the `axis` parameter:**
* `axis=0` performs the operation down the **columns**.
* `axis=1` performs the operation across the **rows**.

In [26]:
a1 = np.random.random((3, 3))
a1 = np.round(a1*100)
print("Base Array (a1):\n", a1)

Base Array (a1):
 [[89. 91. 34.]
 [ 1. 28. 21.]
 [39. 67. 44.]]


In [27]:
# max / min / sum / prod (Global operations on the whole array)
print("\nGlobal Max:", np.max(a1))
print("Global Min:", np.min(a1))
print("Global Sum:", np.sum(a1))
print("Global Product:", np.prod(a1))

# 0 -> col and 1 -> row (Axis-wise operations)
print("\nMax in each row (axis=1):", np.max(a1, axis=1))
print("Max in each col (axis=0):", np.max(a1, axis=0))
print("Min in each col (axis=0):", np.min(a1, axis=0))
print("Sum of each row (axis=1):", np.sum(a1, axis=1))
print("Product of each row (axis=1):", np.prod(a1, axis=1))


Global Max: 91.0
Global Min: 1.0
Global Sum: 414.0
Global Product: 18615715294176.0

Max in each row (axis=1): [91. 28. 67.]
Max in each col (axis=0): [89. 91. 44.]
Min in each col (axis=0): [ 1. 28. 21.]
Sum of each row (axis=1): [214.  50. 150.]
Product of each row (axis=1): [275366.    588. 114972.]


In [28]:
# mean / median / std / var (Statistical operations)
print("\nOverall Mean:", np.mean(a1))
print("Mean of rows (axis=1):", np.mean(a1, axis=1)) 
print("Overall Median:", np.median(a1))
print("Standard Deviation:", np.std(a1)) 
print("Variance:", np.var(a1)) 


Overall Mean: 46.0
Mean of rows (axis=1): [71.33333333 16.66666667 50.        ]
Overall Median: 39.0
Standard Deviation: 28.840557861764356
Variance: 831.7777777777778


In [29]:
# Trigonometric functions (Applies function to every element)
print("\nSine values:\n", np.sin(a1))
# print(np.cos(a1)) # Works identically
# print(np.tan(a1)) # Works identically


Sine values:
 [[ 0.86006941  0.10598751  0.52908269]
 [ 0.84147098  0.27090579  0.83665564]
 [ 0.96379539 -0.85551998  0.01770193]]


In [30]:
# dot product (Matrix Multiplication)
a2 = np.arange(12).reshape(3, 4)
a3 = np.arange(12, 24).reshape(4, 3)
print("\nDot Product of a2 (3x4) and a3 (4x3):\n", np.dot(a2, a3))


Dot Product of a2 (3x4) and a3 (4x3):
 [[114 120 126]
 [378 400 422]
 [642 680 718]]


In [31]:
# log and exponents
print("\nNatural Logarithm:\n", np.log(a1))
print("Exponential (e^x):\n", np.exp(a1))


Natural Logarithm:
 [[4.48863637 4.51085951 3.52636052]
 [0.         3.33220451 3.04452244]
 [3.66356165 4.20469262 3.78418963]]
Exponential (e^x):
 [[4.48961282e+38 3.31740010e+39 5.83461743e+14]
 [2.71828183e+00 1.44625706e+12 1.31881573e+09]
 [8.65934004e+16 1.25236317e+29 1.28516001e+19]]


In [32]:
# round / floor / ceil
random_arr = np.random.random((2, 3)) * 100
print("\nOriginal Random Array:\n", random_arr)
print("Rounded (nearest integer):\n", np.round(random_arr))
print("Floor (rounded down):\n", np.floor(random_arr))
print("Ceil (rounded up):\n", np.ceil(random_arr))


Original Random Array:
 [[76.14929562 18.21291908 87.63114933]
 [13.74352365 69.76472631  7.0436881 ]]
Rounded (nearest integer):
 [[76. 18. 88.]
 [14. 70.  7.]]
Floor (rounded down):
 [[76. 18. 87.]
 [13. 69.  7.]]
Ceil (rounded up):
 [[77. 19. 88.]
 [14. 70.  8.]]
