# 🧠 NumPy Indexing, Slicing & Iterating (Memory Level Guide)

## 🔍 The Memory Secret: Views vs. Copies
Why did modifying `b = a[0:2]` change the original array `a`? 

* **Python Lists (Copy by Default):** Slicing a list allocates fresh RAM and creates a brand-new list.
* **NumPy Arrays (View by Default):** To save RAM, NumPy slicing creates a **View**. It does not allocate new memory; it just points to the exact same physical memory block. 
* **The Fix (`.copy()`):** To safely modify a slice without altering the source data, use `.copy()`.

In [2]:
import numpy as np

## 💻 1D Arrays (Vectors)
Syntax: `array[row_slice]`

In [3]:
# --- 1D ARRAYS ---
a1 = np.arange(10)  # [0 1 2 3 4 5 6 7 8 9]

print("First element:", a1[0])
print("Last element:", a1[-1])
print("Step slicing:", a1[2:5:2])

# ⚠️ The View vs Copy Implementation
b = a1[0:3]       # Creates a 'View'
b[0] = 99         # Changing 'b' WILL change 'a1' in RAM!
print("Original modified by View:", a1)

# ✅ The Safe Way
a1[0] = 0          # Resetting
c = a1[0:3].copy() # Allocates fresh memory
c[0] = 500         # Changes 'c' safely
print("Original safe with Copy:", a1)

First element: 0
Last element: 9
Step slicing: [2 4]
Original modified by View: [99  1  2  3  4  5  6  7  8  9]
Original safe with Copy: [0 1 2 3 4 5 6 7 8 9]


## 💻 2D Arrays (Matrices)
Syntax: `array[row_slice, column_slice]`

In [4]:
a2 = np.arange(12).reshape(3, 4)

print("Single Item:", a2[1, 2])     # Row 1, Column 2
print("Entire Row 0:\n", a2[0, :])  
print("Entire Column 2:\n", a2[:, 2])  
print("2x2 Center Matrix:\n", a2[1:, 1:3])  
print("Corners (Step Slicing):\n", a2[::2, ::3])

Single Item: 6
Entire Row 0:
 [0 1 2 3]
Entire Column 2:
 [ 2  6 10]
2x2 Center Matrix:
 [[ 5  6]
 [ 9 10]]
Corners (Step Slicing):
 [[ 0  3]
 [ 8 11]]


## 🧊 3D Arrays (Tensors)
Syntax: `array[depth_slice, row_slice, column_slice]`

In [5]:
a3 = np.arange(27).reshape(3, 3, 3) 

print("Specific element:", a3[1, 0, 1])  # Depth 1, Row 0, Col 1
print("Skip middle block:\n", a3[::2])            
print("Block 0 -> Row 1 -> All cols:\n", a3[0, 1, :])        
print("Corners from alternate blocks:\n", a3[::2, 0, ::2])

Specific element: 10
Skip middle block:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Block 0 -> Row 1 -> All cols:
 [3 4 5]
Corners from alternate blocks:
 [[ 0  2]
 [18 20]]


## ⚙️ Iterating Over Arrays (CPU Level)
Standard Python `for` loops are slow because they force the CPU to extract elements one by one. `np.nditer` uses NumPy's C-backend to step through the contiguous memory block directly.

In [6]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [8]:
# ❌ The Slow Way (Standard Python Loops)
# for i in a3:         
#     for j in i:      
#         for k in j:  
#             print(k)

# ✅ The Fast Way (np.nditer)
for i in np.nditer(a3):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 