### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1, 100, 15)
a

array([81, 47, 38, 46, 32, 48, 67, 63, 58, 21, 55, 67, 82, 71, 16],
      dtype=int32)

In [5]:
b = np.random.randint(1, 100, 24).reshape(6, 4)
b

array([[92,  5, 92, 89],
       [19, 68, 19,  7],
       [49, 61, 93, 46],
       [16,  8, 11, 19],
       [17, 16, 17, 79],
       [44, 17, 17, 67]], dtype=int32)

In [18]:
np.sort(a)
np.sort(a)[::-1]

array([89, 78, 77, 71, 68, 48, 47, 46, 41, 39, 35, 15, 13,  9,  4],
      dtype=int32)

In [19]:
np.sort(b)
np.sort(b, axis=0)

array([[16,  5, 11,  7],
       [17,  8, 17, 19],
       [19, 16, 17, 46],
       [44, 17, 19, 67],
       [49, 61, 92, 79],
       [92, 68, 93, 89]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a, 200)

array([  9,  71,  39,  47,  78,  13,  46,  15,  68,  41,  35,  48,   4,
        89,  77, 200])

In [30]:
np.append(b, np.ones((b.shape[0], 1)), axis=1)
np.append(b, np.random.random((b.shape[0], 1)), axis=1)

array([[92.        ,  5.        , 92.        , 89.        ,  0.70545616],
       [19.        , 68.        , 19.        ,  7.        ,  0.70337625],
       [49.        , 61.        , 93.        , 46.        ,  0.71158479],
       [16.        ,  8.        , 11.        , 19.        ,  0.89508726],
       [17.        , 16.        , 17.        , 79.        ,  0.83031106],
       [44.        , 17.        , 17.        , 67.        ,  0.43362846]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [31]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c, d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c, d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [34]:
# code
e = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [35]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [36]:
# code
a.shape

(15,)

In [37]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [39]:
np.expand_dims(a, axis=1).shape

(15, 1)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [40]:
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [44]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 1,  4,  8, 13, 14]),)

In [43]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([ 9,  0, 39, 47,  0, 13, 46, 15,  0, 41, 35, 48,  4,  0,  0],
      dtype=int32)

In [49]:
np.where(a % 2 == 0, 0, a)

array([ 9, 71, 39, 47,  0, 13,  0, 15,  0, 41, 35,  0,  0, 89, 77],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [50]:
# code
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [51]:
np.argmax(a)

np.int64(13)

In [54]:
b

array([[92,  5, 92, 89],
       [19, 68, 19,  7],
       [49, 61, 93, 46],
       [16,  8, 11, 19],
       [17, 16, 17, 79],
       [44, 17, 17, 67]], dtype=int32)

In [53]:
np.argmax(b, axis=0)

array([0, 1, 2, 0])

In [55]:
np.argmax(b, axis=1)

array([0, 1, 2, 3, 3, 3])

In [56]:
# np.argmin
np.argmin(a)

np.int64(12)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [57]:
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [58]:
np.cumsum(a)

array([  9,  80, 119, 166, 244, 257, 303, 318, 386, 427, 462, 510, 514,
       603, 680])

In [59]:
b

array([[92,  5, 92, 89],
       [19, 68, 19,  7],
       [49, 61, 93, 46],
       [16,  8, 11, 19],
       [17, 16, 17, 79],
       [44, 17, 17, 67]], dtype=int32)

In [65]:
np.cumsum(b, axis=0)
np.cumsum(b, axis=1)

array([[ 92,  97, 189, 278],
       [ 19,  87, 106, 113],
       [ 49, 110, 203, 249],
       [ 16,  24,  35,  54],
       [ 17,  33,  50, 129],
       [ 44,  61,  78, 145]])

In [61]:
np.cumsum(b)

array([ 92,  97, 189, 278, 297, 365, 384, 391, 440, 501, 594, 640, 656,
       664, 675, 694, 711, 727, 744, 823, 867, 884, 901, 968])

In [66]:
# np.cumprod
np.cumprod(a)

array([                   9,                  639,                24921,
                    1171287,             91360386,           1187685018,
                54633510828,         819502662420,       55726181044560,
           2284773422826960,    79967069798943600,  3838419350349292800,
       -3093066672312380416,  1418227269841417216, -1476964664468184064])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [67]:
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [72]:
np.percentile(a, 100)
np.percentile(a, 0)
np.percentile(a, 50)

np.float64(46.0)

In [69]:
np.median(a)

np.float64(46.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [73]:
# code
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [76]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
np.histogram(a, bins=[0, 50, 100])

(array([10,  5]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [77]:
salary = np.array([20000, 40000, 25000, 35000, 60000])
experience = np.array([1, 3, 2, 4, 2])

np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [79]:
# code
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [84]:
items = [10, 20, 30, 40, 50, 60, 71, 80, 90, 100]

np.isin(a, items)
a[np.isin(a, items)]

array([71], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [85]:
# code
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [86]:
np.flip(a)

array([77, 89,  4, 48, 35, 41, 68, 15, 46, 13, 78, 47, 39, 71,  9],
      dtype=int32)

In [88]:
b

array([[92,  5, 92, 89],
       [19, 68, 19,  7],
       [49, 61, 93, 46],
       [16,  8, 11, 19],
       [17, 16, 17, 79],
       [44, 17, 17, 67]], dtype=int32)

In [96]:
np.flip(b)
np.flip(b, axis=0)
np.flip(b, axis=1)

array([[89, 92,  5, 92],
       [ 7, 19, 68, 19],
       [46, 93, 61, 49],
       [19, 11,  8, 16],
       [79, 17, 16, 17],
       [67, 17, 17, 44]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [97]:
# code
a

array([ 9, 71, 39, 47, 78, 13, 46, 15, 68, 41, 35, 48,  4, 89, 77],
      dtype=int32)

In [101]:
np.put(a, [0, 1], [110, 530]) # permanent changes
a

array([110, 530,  39,  47,  78,  13,  46,  15,  68,  41,  35,  48,   4,
        89,  77], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [102]:
# code
a

array([110, 530,  39,  47,  78,  13,  46,  15,  68,  41,  35,  48,   4,
        89,  77], dtype=int32)

In [104]:
np.delete(a, [0, 2, 4])

array([530,  47,  13,  46,  15,  68,  41,  35,  48,   4,  89,  77],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [107]:
m = np.array([1, 2, 3, 4, 5])
n = np.array([3, 4, 5, 6, 7])

np.union1d(m, n)

array([1, 2, 3, 4, 5, 6, 7])

In [106]:
np.intersect1d(m, n)

array([3, 4, 5])

In [112]:
np.setdiff1d(n, m)

array([6, 7])

In [114]:
np.setxor1d(m, n)

array([1, 2, 6, 7])

In [ ]:
# m[np.in1d(m, 1)]

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [116]:
# code
a

array([110, 530,  39,  47,  78,  13,  46,  15,  68,  41,  35,  48,   4,
        89,  77], dtype=int32)

In [117]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 39, 47, 75, 25, 46, 25, 68, 41, 35, 48, 25, 75, 75],
      dtype=int32)

In [7]:
# 17. np.swapaxes

# Create a 2D array with 2 rows and 3 columns
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Swap axis 0 (rows) with axis 1 (columns)
swapped = np.swapaxes(arr, 0, 1)
print(swapped)

[[1 4]
 [2 5]
 [3 6]]


In [8]:
# 18. np.uniform

# Generate 5 random decimal numbers between 1 and 10
random_nums = np.random.uniform(1, 10, 5)
print(random_nums)

[5.56843859 1.278174   2.20175817 1.33741537 3.37963799]


In [9]:
# 19. np.count_nonzero

# An array containing some 0s
arr = np.array([0, 5, 0, 10, 20, 0])

# Count how many numbers are not 0
count = np.count_nonzero(arr)
print(count)

3


In [10]:
# 21. np.tile

arr = np.array([1, 2])

# Repeat this array 3 times
tiled = np.tile(arr, 3)
print(tiled)

# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

[1 2 1 2 1 2]


In [15]:
# 22. np.repeat

# Create a simple array
arr = np.array([1, 2, 3])

# Repeat each individual element 2 times
repeated_arr = np.repeat(arr, 2)
print(repeated_arr)

# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

[1 1 2 2 3 3]


In [18]:

# 25. np.allclose and equals

# Two arrays that are mathematically the same but have a tiny floating-point difference
arr1 = np.array([0.1 + 0.2])
arr2 = np.array([0.3])

# Check if they are exactly equal
exact_match = np.array_equal(arr1, arr2)
print("Exact match:", exact_match)

# Check if they are close enough (ignoring tiny decimal differences)
close_match = np.allclose(arr1, arr2)
print("Close match:", close_match)

Exact match: False
Close match: True
